apiVersion: v1
kind: ConfigMap
metadata:
  name: default-pod-annotations-configmap
  namespace: system
data:
  annotations.yaml: |
    qpoint.io/inject-ca: "true"
    qpoint.io/egress-to-domain: "qtap.qpoint.svc.cluster.local"

