apiVersion: v1
kind: ConfigMap
metadata:
  name: service-pod-annotations-configmap
  namespace: system
data:
  annotations.yaml: |
    qpoint.io/inject-ca: "true"
    qpoint.io/egress-init-tag: "v0.0.7"
    qpoint.io/egress-to-domain: "qtap-gateway.qpoint.svc.cluster.local"
    qpoint.io/egress-port-mapping: "10080:80,10443:443"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inject-pod-annotations-configmap
  namespace: system
data:
  annotations.yaml: |
    qpoint.io/inject-ca: "true"
    qpoint.io/egress-init-tag: "v0.0.7"
    qpoint.io/qtap-tag: "v0.0.10"
    qpoint.io/egress-port-mapping: "10080:80,10443:443,10000:"
    qpoint.io/log-level: "info"
    qpoint.io/block-unknown: "false"
    qpoint.io/dns-lookup-family: "V4_ONLY"
    qpoint.io/qtap-uid: "1010"
    qpoint.io/qtap-gid: "1010"
