apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world-container
    image: curlimages/curl
    command: ['sh', '-c', 'echo Hello World! && sleep 3600']
  # - name: hello-world-container
  #   image: ubuntu:latest
  #   command: ['sh', '-c', 'echo Hello World! && sleep 3600']
